version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
  dashboard:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
